- name: Install GPG Dependency
  apt: name=gnupg2 state=latest
- name: Install Python Dependency
  apt: name=python3-apt state=latest
- name: Add the Docker GPG apt Key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present
- name: Add the Docker Repository
  apt_repository: repo="deb https://download.docker.com/linux/ubuntu jammy stable" state=present
  register: apt_repository_output
- name: Install FastTrack
  apt: name=fasttrack-archive-keyring state=latest update_cache=true
- name: Install FastTrack Repo
  apt_repository: repo="deb https://fasttrack.debian.net/debian-fasttrack/ bookworm-fasttrack main contrib" state=present

- name: Install apt packages.
  ansible.builtin.apt:
    pkg: "{{ apt.packages }}"
    state: present
    update_cache: true
  tags: apt

- name: Update apt packages
  ansible.builtin.apt:
    upgrade: full

- name: Adding user flippy
  ansible.builtin.user:
    name: flippy
    #    group: flippy
    shell: /usr/bin/fish
    password: "{{ 'f' | password_hash('sha512') }}"
    groups: sudo, docker
    append: yes

- name: Create Docker volumes
  docker_volume:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_volumes }}"

- name: Create Docker network
  docker_volume:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_network }}"


- name: Install Dockcheck
  ansible.builtin.git:
    repo: https://github.com/mag37/dockcheck.git
    dest: /opt/docker/dockcheck




    # dot flies
    # homebrew eza

